services:
  kestra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kestra
    ports:
      - "8080:8080"
    command: server local
    volumes:
      - ./dbt_instacart:/app/dbt_instacart
      - ./data_ingestion:/app/data_ingestion
      - kestra-data:/app/storage
      - /tmp:/tmp

  postgres:
    image: postgres:15
    container_name: instacart_postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instacart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  kestra-data: